-- Analyst notes (Phase 6c).
--
-- One row per (ticker, week_start) — a weekly per-ticker synthesis
-- generated by the LLM. Re-running the same week overwrites the row via
-- `INSERT OR REPLACE` in the store; a rerun mid-week produces a fresher
-- take on the same week's data, which is what a reader expects. Storing
-- history by `week_start` means the archive on the tab keeps prior
-- weeks intact.
--
-- `context_json` is the structured input the model saw (recent news +
-- financials + ratios + price stats + snapshot) so a future re-run with
-- a different prompt doesn't need to re-gather the source data.
--
-- Cost accounting for the notes writer lives in its own `note_spend`
-- table so a per-ticker weekly run can't drain the daily-brief cap or
-- the tagger's cap.

CREATE TABLE IF NOT EXISTS analyst_notes (
    ticker           TEXT NOT NULL REFERENCES securities(ticker),
    week_start       TEXT NOT NULL,          -- 'YYYY-MM-DD' Monday (ISO week)
    model            TEXT NOT NULL,          -- claude-sonnet-4-6 / -haiku-4-5 / ...
    title            TEXT,                   -- optional one-liner subject
    markdown         TEXT NOT NULL,          -- body content
    context_json     TEXT NOT NULL,          -- snapshot of inputs
    input_tokens     INTEGER NOT NULL DEFAULT 0,
    output_tokens    INTEGER NOT NULL DEFAULT 0,
    usd_micros       INTEGER NOT NULL DEFAULT 0,
    generated_utc    TEXT NOT NULL,
    PRIMARY KEY (ticker, week_start)
);

CREATE INDEX IF NOT EXISTS ix_analyst_notes_ticker_week
    ON analyst_notes(ticker, week_start DESC);
CREATE INDEX IF NOT EXISTS ix_analyst_notes_week
    ON analyst_notes(week_start DESC);

-- Separate daily counter for the notes writer. Same shape as
-- llm_spend / filings_spend / brief_spend after 0004.
CREATE TABLE IF NOT EXISTS note_spend (
    day             TEXT PRIMARY KEY,       -- 'YYYY-MM-DD' UTC
    calls           INTEGER NOT NULL DEFAULT 0,
    input_tokens    INTEGER NOT NULL DEFAULT 0,
    output_tokens   INTEGER NOT NULL DEFAULT 0,
    usd_cents       INTEGER NOT NULL DEFAULT 0,
    usd_micros      INTEGER NOT NULL DEFAULT 0
);
