-- PR-H: prospectus URL on `securities`.
--
-- Bloomberg-style bond overview wants a single "prospectus" link, not
-- a scrolling list of every admission communiqué. This column pins the
-- canonical URL per bond ticker.
--
-- Populated by `scripts/backfill_prospectus.py`, which walks the
-- brvm.org avis feed (`/fr/marche/avis-et-publications/avis`) and
-- pins the "Première cotation" admission PDF per ticker. The exchange
-- does not host the full note d'information — the admission avis is
-- the closest public substitute unambiguously tied to a specific
-- listing. Users can manually override the pin with a real prospectus
-- URL when one is known.
--
-- No seed here: the earlier revision tried to backfill from
-- `news_items` matching `_list_prospectus_news`, but `news_items`
-- issuer_name uses equity-style long names (SONATEL, PALMCI) while
-- bond `securities.issuer_name` uses bond-style codes (TPCI, ETAT DU
-- MALI, CRRH-UEMOA), so the join never fired. Backfill script is the
-- correct path.

ALTER TABLE securities ADD COLUMN prospectus_url TEXT;
